services:
# Web Server Service

  cms-database:
    container_name: cms-database
    build: .
    volumes:
      - .:/var/www/html/
    ports:
      - 7001:80

  db:
    image: postgres
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment: 
      POSTGRES_DB: cms-database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: congkaka123

volumes:
  db_data:
